services:
  mongo:
    image: mongo:6           
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"          
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db  
    networks:
      - mongo_net
      
  python:
    image: python:3.11-slim
    container_name: python
    volumes:
      - ./scripts:/app     
      - ./data:/data       
    depends_on:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_RW_USER: ${MONGO_RW_USER}
      MONGO_RW_PASS: ${MONGO_RW_PASS}
      MONGO_READ_USER: ${MONGO_READ_USER}
      MONGO_READ_PASS: ${MONGO_READ_PASS}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      PYTHONDONTWRITEBYTECODE: 1
    networks:
      - mongo_net
    stdin_open: true
    tty: true
    command: bash -c "pip install --no-cache-dir -r app/requirements.txt && python3 app/mongo_users_create.py && bash"


  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo_net
      
volumes:
  mongo_data:

networks:
  mongo_net:
    driver: bridge

