services:
  mongo:
    image: mongo:6           
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"          
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db  
    networks:
      - mongo_net
      
  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo_net
      
volumes:
  mongo_data:

networks:
  mongo_net:
    driver: bridge

